import type { Metadata } from "next";
import Link from "next/link";

import { CodeBlock } from "@/components/site/code-block";
import { ButtonBase } from "@/components/ui/button-base";
import { Separator } from "@/components/ui/separator";
import { siteConfig } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Documentation",
  description: "How B6 UI is built: design tokens, architecture, and adding a component.",
};

const tokenGroups = [
  {
    name: "Colour",
    body: "Semantic only — background, foreground, card, popover, primary, secondary, muted, accent, destructive, border, input, ring, each with a foreground pair where it carries text. Defined in oklch in `app/globals.css` and exposed to Tailwind through `@theme inline`.",
  },
  {
    name: "Typography",
    body: "Eight steps: display, h1, h2, h3, body, small, caption, code. Each step ships its own line-height, tracking and weight, so `text-h2` is a complete type decision.",
  },
  {
    name: "Spacing",
    body: "Tailwind's 0.25rem scale, unmodified. Component internals stay on multiples of 2 (0.5rem) so controls align on a shared baseline.",
  },
  {
    name: "Radius",
    body: "Derived from one `--b6-radius` base: `rounded-xs`, `rounded-sm`, `rounded-md`, `rounded-lg`, `rounded-xl`. Change the base and the whole system re-rounds.",
  },
  {
    name: "Elevation",
    body: "Four shadows — `shadow-b6-xs` through `shadow-b6-lg`. Surfaces rise only when they are interactive or overlaying.",
  },
  {
    name: "Motion",
    body: "Two easing curves (`ease-b6`, `ease-b6-out`) and five named animations: fade, slide, scale, expand, collapse. Everything honours `prefers-reduced-motion`.",
  },
];

const architecture = `Component source        registry/<slug>/<slug>.tsx      ← single source of truth
Site import             components/ui/<slug>.tsx       ← re-export
Preview                 components/previews/<slug>-preview.tsx
Docs metadata           lib/registry.ts
Registry definition     registry.json
Built registry JSON     public/r/<slug>.json           ← generated by \`shadcn build\`
Consumer                components/ui/<slug>.tsx       ← written by \`shadcn add\``;

const newComponent = `# 1. Write the component — this file is what consumers receive.
registry/toggle/toggle.tsx

# 2. Re-export it for the docs site.
components/ui/toggle.tsx

# 3. Add a preview and register it.
components/previews/toggle-preview.tsx
components/previews/index.ts

# 4. Document it.
lib/registry.ts       -> add a ComponentMeta entry
registry.json         -> add a registry item

# 5. Rebuild the registry and verify.
bun run registry:build
bun run test
bun run lint && bun run build`;

export default function DocsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <header>
        <h1 className="text-h1">Documentation</h1>
        <p className="mt-3 text-muted-foreground">
          {siteConfig.name} is a component library you install as source code. This page covers
          the design system it is built on and how to extend it.
        </p>
      </header>

      <Separator className="my-10" decorative={false} />

      <section aria-labelledby="tokens-heading">
        <h2 id="tokens-heading" className="text-h2">
          Design tokens
        </h2>
        <p className="mt-2 text-muted-foreground">
          Components reference tokens, never raw values. That is the whole reason a B6 component
          drops into a project and immediately looks like the rest of it.
        </p>
        <dl className="mt-6 flex flex-col gap-5">
          {tokenGroups.map((group) => (
            <div key={group.name}>
              <dt className="text-h3">{group.name}</dt>
              <dd className="mt-1 text-small text-muted-foreground">{group.body}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="mt-12" aria-labelledby="architecture-heading">
        <h2 id="architecture-heading" className="text-h2">
          Architecture
        </h2>
        <p className="mt-2 text-muted-foreground">
          Component logic exists once. Everything else points at it.
        </p>
        <CodeBlock
          className="mt-4"
          code={architecture}
          filename="architecture"
          language="text"
        />
      </section>

      <section className="mt-12" aria-labelledby="adding-heading">
        <h2 id="adding-heading" className="text-h2">
          Adding a component
        </h2>
        <p className="mt-2 text-muted-foreground">
          Five files, in this order. The slug is the contract — folder name, export path, docs
          URL and install argument all use it.
        </p>
        <CodeBlock className="mt-4" code={newComponent} filename="checklist" language="text" />
      </section>

      <section className="mt-12" aria-labelledby="next-heading">
        <h2 id="next-heading" className="text-h2">
          Next
        </h2>
        <div className="mt-4 flex flex-wrap gap-3">
          <ButtonBase asChild>
            <Link href="/docs/installation">Installation</Link>
          </ButtonBase>
          <ButtonBase asChild variant="outline">
            <Link href="/components">Components</Link>
          </ButtonBase>
        </div>
      </section>
    </div>
  );
}
