import type { Metadata } from "next";
import Link from "next/link";

import { CodeBlock } from "@/components/site/code-block";
import { DocsSection } from "@/components/site/docs-section";
import { Toc, type TocItem } from "@/components/site/toc";
import { ButtonBase } from "@/components/ui/button-base";
import { siteConfig } from "@/lib/constants";

/** Section index for the right-hand column. Mirrors the section ids below. */
const tocItems: TocItem[] = [
  { id: "tokens", label: "Design tokens" },
  { id: "architecture", label: "Architecture" },
  { id: "adding", label: "Adding a component" },
  { id: "next", label: "Next" },
];

export const metadata: Metadata = {
  title: "Documentation",
  description: "How B6 UI is built: design tokens, architecture, and adding a component.",
};

const tokenGroups = [
  {
    name: "Colour",
    body: "Semantic only: background, foreground, card, popover, primary, secondary, muted, accent, destructive, border, input, ring, each with a foreground pair where it carries text. Defined in oklch in `app/globals.css` and exposed to Tailwind through `@theme inline`.",
  },
  {
    name: "Typography",
    body: "Eight steps: display, h1, h2, h3, body, small, caption, code. Each step ships its own line-height, tracking and weight, so `text-h2` is a complete type decision.",
  },
  {
    name: "Spacing",
    body: "Tailwind's 0.25rem scale, unmodified. Component internals stay on multiples of 2 (0.5rem) so controls align on a shared baseline.",
  },
  {
    name: "Radius",
    body: "Derived from one `--b6-radius` base: `rounded-xs`, `rounded-sm`, `rounded-md`, `rounded-lg`, `rounded-xl`. Change the base and the whole system re-rounds.",
  },
  {
    name: "Elevation",
    body: "Four shadows, `shadow-b6-xs` through `shadow-b6-lg`. Surfaces rise only when they are interactive or overlaying.",
  },
  {
    name: "Motion",
    body: "Two easing curves (`ease-b6`, `ease-b6-out`) and five named animations: fade, slide, scale, expand, collapse. Everything honours `prefers-reduced-motion`.",
  },
];

const architecture = `Component source        registry/<family>/<slug>/<slug>.tsx   ← single source of truth
Site import             components/ui/<slug>.tsx       ← re-export
Preview                 components/previews/<slug>-preview.tsx
Docs metadata           lib/registry.ts
Registry definition     registry.json
Built registry JSON     public/r/<slug>.json           ← generated by \`shadcn build\`
Consumer                components/ui/<slug>.tsx       ← written by \`shadcn add\``;

const newComponent = `# 1. Write the component. This file is what consumers receive.
# <family> is the noun the component varies on: toggle, button, card…
registry/toggle/toggle/toggle.tsx

# 2. Re-export it for the docs site.
components/ui/toggle.tsx

# 3. Add a preview and register it.
components/previews/toggle-preview.tsx
components/previews/index.ts

# 4. Document it.
lib/registry.ts       -> add a ComponentMeta entry
registry.json         -> add a registry item

# 5. Rebuild the registry and verify.
bun run registry:build
bun run test
bun run lint && bun run build`;

export default function DocsPage() {
  return (
    <>
      <article className="min-w-0 pb-16 lg:py-12">
        <header>
          <h1 className="text-h1">Documentation</h1>
          <p className="mt-3 max-w-2xl text-muted-foreground">
            {siteConfig.name} is a component library you install as source code. This page
            covers the design system it is built on and how to extend it.
          </p>
        </header>

        <DocsSection
          id="tokens"
          title="Design tokens"
          description="Components reference tokens, never raw values. That is the whole reason a B6 component drops into a project and immediately looks like the rest of it."
        >
          <dl className="flex flex-col gap-5">
            {tokenGroups.map((group) => (
              <div key={group.name}>
                <dt className="text-h3">{group.name}</dt>
                <dd className="mt-1 text-small text-muted-foreground">{group.body}</dd>
              </div>
            ))}
          </dl>
        </DocsSection>

        <DocsSection
          id="architecture"
          title="Architecture"
          description="Component logic exists once. Everything else points at it."
        >
          <CodeBlock code={architecture} filename="architecture" language="text" />
        </DocsSection>

        <DocsSection
          id="adding"
          title="Adding a component"
          description="Five files, in this order. The slug is the contract: folder name, export path, docs URL and install argument all use it."
        >
          <CodeBlock code={newComponent} filename="checklist" language="text" />
        </DocsSection>

        <DocsSection id="next" title="Next">
          <div className="flex flex-wrap gap-3">
            <ButtonBase asChild>
              <Link href="/docs/installation">Installation</Link>
            </ButtonBase>
            <ButtonBase asChild variant="outline">
              <Link href="/components">Components</Link>
            </ButtonBase>
          </div>
        </DocsSection>
      </article>

      <Toc items={tocItems} />
    </>
  );
}
